mod_version_suffix=6.0.x

minecraft_version=1.21.1
loader_version=0.19.1
fabric_api_version=0.116.11+1.21.1
parchment_version=2024.11.17

create_fabric_group=com.simibubi.create
create_fabric_artifact_id=create-fabric-1.21.1
create_fabric_version=6.0.0.0+mc1.21.1-local
forgeconfigapiport_group=fuzs.forgeconfigapiport
forgeconfigapiport_artifact_id=forgeconfigapiport-fabric
forgeconfigapiport_fabric_version=21.1.3
night_config_version=3.8.3
java_version=21
