# beta alpha release
# Information
mod_version = 0.2.8.2-0.5.1i


# Mod Versions
curseforge_id = 1256076
modrinth_id = 43gwKokf

mod_id = createentitycontrol
mod_name = Create:Entity Control
package_name = CreateEntityControl
mod_group_id = com.Pink_Cats
mod_author = Pink_Cats
mod_license = MIT
display_name = CEC
mod_description = A simple mod that adds more parameters to the Create mobile structure, which can prevent some Create and attached mobile structure bugs
publish_version = release

# dependency versions
jei_minecraft_version = 1.20.1
jei_version = 15.19.0.85
curios_minecraft_version = 1.20.1
curios_version = 5.3.1
jade_id = 6106101
architectury_version=9.1.12
rhino_version=2001.2.3-build.10
kubejs_version=2001.6.5-build.17
mixin_extras_version = 0.4.1



minecraft_version = 1.19.2
forge_version = 43.2.4
forge_version_range = [43,)
loader_version_range = [43,)


registrate_version = MC1.19-1.1.5
parchment_version = 2022.11.27


# gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.logging.level=quiet