modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
[[mods]]
    modId = "${mod_id}" #mandatory
    version = "0.2.5-0.5.1j" #mandatory
    displayName = "${mod_name}" #mandatory
    authors = "Pink_Cats" #optional
    logoFile="icon.png"
    description = '''${mod_description}'''
    displayURL="https://www.curseforge.com/minecraft/mc-mods/create-entitycontroller"

[[dependencies."${mod_id}"]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.0.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.f,0.5.2)"
    ordering="NONE"
    side="BOTH"

