
# Mod Versions
mod_version=0.3.8.4-6.0.x
mod_id=createentitycontrol
mod_name=Create:Entity Control
package_name = CreateEntityControl
mod_group_id=com.Pink_Cats
mod_authors=Pink_Cats
mod_license=MIT
display_name=CEC
mod_description=A simple mod that adds more parameters to the Create mobile structure, which can prevent some Create and attached mobile structure bugs
publish_version = release

# other version
create_version = 6.0.6-98
ponder_version = 1.0.56
flywheel_version = 1.0.4
registrate_version = MC1.21-1.3.0+62
jei_version=19.21.2.313

# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# base
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.209
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# publish
curseforge_id = 1256076
modrinth_id = 43gwKokf