# Shared mod metadata for all supported loader/version variants.
mod_id=createentitycontrol
package_name=CreateEntityControl
mod_name=Create:Entity Control
mod_license=MIT
mod_base_version=0.6.16.9
mod_group_id=com.Pink_Cats
mod_author=Pink_Cats
mod_authors=Pink_Cats
display_name=CEC
mod_description=A simple mod that adds more parameters to the Create mobile structure, which can prevent some Create and attached mobile structure bugs

# Publishing
curseforge_id=1256076
modrinth_id=43gwKokf
publish_version=release

# Shared dependency versions
mixin_extras_version=0.4.1
architectury_version=9.1.12
rhino_version=2001.2.3-build.10
kubejs_version=2001.6.5-build.17
curios_minecraft_version=1.20.1
curios_version=5.3.1
jade_id=6106101

# Optional integration dependency versions used by Forge 1.20.1 variants.
cc_tweaked_enable=false
cc_tweaked_minecraft_version=1.20.1
cc_tweaked_version=1.105.0
ct_enabled=true
ct_minecraft_version=1.20.1
ct_version=14.0.17
ct_annotation_processor_version=3.0.0.15
ct_create_version=4.0.15
ct_create_id=4548572
