mod_version_suffix=0.5.1i

minecraft_version=1.19.2
loader_version=0.15.11
fabric_api_version=0.77.0+1.19.2
parchment_version=2022.11.27

create_fabric_group=com.simibubi.create
create_fabric_artifact_id=create-fabric-1.19.2
create_fabric_version=0.5.1-i-build.1630+mc1.19.2
porting_lib_version=2.1.1453+1.19.2
registrate_fabric_version=1.1.58-MC1.19.2
flywheel_fabric_version=0.6.11-9
forgeconfigapiport_group=net.minecraftforge
forgeconfigapiport_artifact_id=forgeconfigapiport-fabric
forgeconfigapiport_fabric_version=4.2.11
reach_entity_attributes_version=2.3.0
milk_lib_version=1.0.51
java_version=17

night_config_version=3.6.6

