mod_version_suffix=6.0.x

minecraft_version=1.20.1
loader_version=0.17.2
fabric_api_version=0.92.6+1.20.1
parchment_version=2023.09.03

create_fabric_group=maven.modrinth
create_fabric_artifact_id=create-fabric
create_fabric_version=6.0.8.1+build.1744-mc1.20.1
porting_lib_version=
registrate_fabric_version=
flywheel_fabric_version=
ponder_fabric_version=
forgeconfigapiport_group=fuzs.forgeconfigapiport
forgeconfigapiport_artifact_id=forgeconfigapiport-fabric
forgeconfigapiport_fabric_version=8.0.0
night_config_version=3.6.3
reach_entity_attributes_version=
milk_lib_version=
java_version=17

