mod_version_suffix=6.0.x

minecraft_version=1.20.1
loader_version=0.17.2
fabric_api_version=0.92.6+1.20.1
parchment_version=2023.09.03

create_fabric_group=maven.modrinth
create_fabric_artifact_id=create-fabric
create_fabric_version=6.0.8.1+build.1744-mc1.20.1
porting_lib_version=2.3.13+1.20.1
registrate_fabric_version=1.3.79-MC1.20.1
flywheel_fabric_version=1.0.5-264
ponder_fabric_version=1.0.91
forgeconfigapiport_group=fuzs.forgeconfigapiport
forgeconfigapiport_artifact_id=forgeconfigapiport-fabric
forgeconfigapiport_fabric_version=8.0.0
night_config_version=3.6.3
reach_entity_attributes_version=2.4.0
milk_lib_version=1.2.60
java_version=17

